[platformio]
default_envs = t5_pro_receiver
packages_dir = .pio-packages

[env:t5_pro_receiver]
platform = espressif32@6.5.0
board = T5-ePaper-S3
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DBOARD_HAS_PSRAM
    -DPSRAM_SPEED=120MHz
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -Wl,--gc-sections

lib_deps =
    m5stack/M5GFX@0.2.24
    lewisxhe/XPowersLib@0.2.7
