#pragma once
#ifdef ESP_PLANTS_H2_COMPAT_BRIDGE_ALPHA23
#define ESP_PLANTS_H2_VERSION "0.2.0-alpha.23"
#define ESP_PLANTS_H2_BUILD_ID "ESPPLANTS-H2-0.2.0-alpha.23"
#else
#define ESP_PLANTS_H2_VERSION "0.2.0-alpha.24"
#define ESP_PLANTS_H2_BUILD_ID "ESPPLANTS-H2-0.2.0-alpha.24"
#endif
#define ESP_PLANTS_H2_HARDWARE_ID "m5stack-unit-gateway-h2"
#define ESP_PLANTS_H2_PRODUCT_ID "esp-plants-h2"
#define ESP_PLANTS_H2_RELEASE_MARKER "ESP-PLANTS-H2-DISTRIBUTION-BUILD"
#ifdef ESP_PLANTS_DISTRIBUTION_BUILD
#define ESP_PLANTS_H2_DISTRIBUTION_MARKER ESP_PLANTS_H2_RELEASE_MARKER
#else
#define ESP_PLANTS_H2_DISTRIBUTION_MARKER "ESP-PLANTS-H2-DEVELOPMENT-BUILD"
#endif
