#pragma once
#define ESP_PLANTS_H2_VERSION "0.2.0-alpha.18"
#define ESP_PLANTS_H2_HARDWARE_ID "m5stack-unit-gateway-h2"
#define ESP_PLANTS_H2_PRODUCT_ID "esp-plants-h2"
#define ESP_PLANTS_H2_BUILD_ID "ESPPLANTS-H2-" ESP_PLANTS_H2_VERSION
#ifdef ESP_PLANTS_DISTRIBUTION_BUILD
#define ESP_PLANTS_H2_DISTRIBUTION_MARKER "ESP-PLANTS-H2-DISTRIBUTION-BUILD"
#else
#define ESP_PLANTS_H2_DISTRIBUTION_MARKER "ESP-PLANTS-H2-DEVELOPMENT-BUILD"
#endif
