#pragma once
#include <Arduino.h>
namespace espplants_phrases {
enum class Theme:uint8_t { CLASSIC=0,FUNNY=1,SARCASTIC=2,DRAMATIC=3,RUDE=4,MIXED=5 };
enum class State:uint8_t { CRITICAL=0,VERY_DRY=1,DRY=2,GOOD=3,WET=4,VERY_WET=5 };
struct Rotation { uint8_t state=0xff; uint16_t cursor=0,step=1,offset=0; };
inline State stateFor(uint8_t m,bool warning){ if(warning||m<=10)return State::CRITICAL;if(m<=20)return State::VERY_DRY;if(m<=40)return State::DRY;if(m<=70)return State::GOOD;if(m<=85)return State::WET;return State::VERY_WET; }
static const char *const kCLASSIC_CRITICAL[]={
  "Emergency drink required.",
  "Soil moisture is critically low.",
  "I need water now.",
  "Please water me as soon as possible.",
  "My soil is extremely dry.",
  "Critical moisture level reached.",
  "I'm running out of water.",
  "This plant needs immediate attention.",
  "Water level: critically low.",
  "I'm seriously thirsty.",
  "Please don't make me wait.",
  "A good soak would help right now.",
  "Water this plant immediately.",
  "Severe dehydration is underway.",
  "Moisture is at emergency levels.",
  "Please soak the soil right now.",
  "Roots have almost no water left.",
  "Do not delay watering any longer.",
  "This plant is in water crisis.",
  "Soil is dangerously dry.",
  "Urgent watering is required.",
  "Hydration cannot wait.",
  "The soil is past safe dryness.",
  "Please water before damage sets in.",
  "Moisture has collapsed.",
  "This is a watering emergency.",
  "Soil water is nearly gone.",
  "Immediate hydration is needed.",
  "The plant is under severe water stress.",
  "Please give a thorough soak now.",
  "Critical dryness has set in.",
  "Water now to protect the roots.",
  "Moisture is unsafe at this level.",
  "The soil cannot support the plant.",
  "Please act on this drought now.",
  "Rescue watering is needed.",
};
static const char *const kCLASSIC_VERY_DRY[]={
  "I'm very thirsty.",
  "My soil is getting seriously dry.",
  "Water would be appreciated soon.",
  "I'm getting parched.",
  "It's definitely time for a drink.",
  "Moisture is well below comfortable.",
  "I'm asking nicely: water, please.",
  "Things are getting dry down here.",
  "A drink should be on the schedule.",
  "I'm not critical yet, but close.",
  "My roots could use some water.",
  "Please check my soil soon.",
  "Moisture is very low.",
  "Please plan to water soon.",
  "The soil is much too dry.",
  "Thirst is getting serious.",
  "A watering should happen shortly.",
  "Roots are running short on water.",
  "This plant is close to critical.",
  "Please do not put watering off long.",
  "Soil moisture needs a refill soon.",
  "Dryness is becoming a problem.",
  "Water would help a lot right now.",
  "The plant is very thirsty.",
  "Please check the watering can soon.",
  "Soil conditions are uncomfortably dry.",
  "A drink is needed before long.",
  "Moisture has dropped well below ideal.",
  "Please water before it becomes critical.",
  "The roots need moisture soon.",
  "This soil is approaching emergency dryness.",
  "Hydration should be next on the list.",
  "Please give the soil a good drink soon.",
  "Very little water remains in the pot.",
  "The plant is asking for water now.",
  "Dry soil is starting to stress the plant.",
};
static const char *const kCLASSIC_DRY[]={
  "Getting a little thirsty.",
  "I could use a drink.",
  "My soil is starting to dry out.",
  "Water me when you get a chance.",
  "I'm getting toward the dry side.",
  "A little water would be nice.",
  "Moisture is dropping.",
  "I'm ready for my next drink.",
  "Not desperate, just thirsty.",
  "My roots are asking for a refill.",
  "It's almost watering time.",
  "Keep an eye on my moisture.",
  "Soil is on the dry side.",
  "A watering is coming due.",
  "Please water when convenient.",
  "Moisture could use a top-up.",
  "The plant would like a drink soon.",
  "Dryness is starting to show.",
  "Roots would welcome a refill.",
  "Watering time is approaching.",
  "Please plan a modest watering.",
  "The soil is no longer comfortably moist.",
  "A light soak would help.",
  "Moisture has slipped below ideal.",
  "This plant can wait a little, not long.",
  "Please add water in the near term.",
  "The pot is drying out gradually.",
  "Thirst is mild but rising.",
  "A drink would restore comfort.",
  "Please keep watering on the agenda.",
  "Soil moisture is trending down.",
  "The plant is ready for more water.",
  "Not urgent, but watering is due.",
  "Please do not forget this pot.",
  "A routine watering would suffice.",
  "The soil could use attention soon.",
};
static const char *const kCLASSIC_GOOD[]={
  "Doing good.",
  "Moisture feels just right.",
  "I'm happy right here.",
  "No water needed right now.",
  "Everything is comfortable.",
  "Roots are happy.",
  "I'm in the sweet spot.",
  "All good down here.",
  "Moisture level looks great.",
  "I'm doing just fine.",
  "This is a comfortable amount of water.",
  "Nothing needed from you right now.",
  "Moisture is in the ideal range.",
  "No watering is needed.",
  "The soil feels well balanced.",
  "This plant is settled and fine.",
  "Roots have the water they need.",
  "Conditions look healthy.",
  "Please leave the watering can aside.",
  "Moisture is holding nicely.",
  "The plant is comfortable.",
  "Water level is just right.",
  "Nothing to adjust right now.",
  "Soil moisture is on target.",
  "The plant can stay as it is.",
  "Hydration looks healthy.",
  "Please wait before watering.",
  "The soil is in good shape.",
  "Comfortable moisture throughout.",
  "No action required at this time.",
  "The plant is content.",
  "Water needs are currently met.",
  "This reading is a healthy one.",
  "Soil conditions are stable.",
  "The roots are well supplied.",
  "Keep the current watering pause.",
};
static const char *const kCLASSIC_WET[]={
  "Nice and moist.",
  "I've got plenty of water.",
  "No refill needed.",
  "I'm well watered.",
  "Moisture is on the high side.",
  "I'm good for a while.",
  "Plenty of water down here.",
  "You can skip watering me.",
  "My soil is comfortably wet.",
  "Water supply looks generous.",
  "I'm definitely not thirsty.",
  "Let me use what I have first.",
  "Soil moisture is still high.",
  "Please wait before watering again.",
  "The plant has ample water.",
  "No drink is needed yet.",
  "Moisture reserves are strong.",
  "The soil is still quite wet.",
  "Please let the plant use what it has.",
  "Watering can wait.",
  "Roots have more than enough for now.",
  "The pot is well supplied.",
  "Moisture is above the ideal band.",
  "Skip watering this round.",
  "The soil remains generously moist.",
  "Please hold the watering can.",
  "The plant is not thirsty.",
  "There is plenty of water stored.",
  "Soil is wet enough to last.",
  "A watering now would be extra.",
  "Let the current moisture work.",
  "The plant is well hydrated.",
  "Please check again later, not now.",
  "Moisture is still on the wet side.",
  "No refill is required.",
  "The soil can rest from watering.",
};
static const char *const kCLASSIC_VERY_WET[]={
  "I'm very wet right now.",
  "Please hold off on watering.",
  "My soil is saturated.",
  "Definitely no more water yet.",
  "I have more than enough water.",
  "Let me dry out a little.",
  "The soil is extremely wet.",
  "Watering can take a break.",
  "I'm full, thanks.",
  "Roots have plenty to work with.",
  "No water needed for quite a while.",
  "Please give the soil time to dry.",
  "Soil is overly saturated.",
  "Please stop watering for now.",
  "There is far too much water.",
  "Allow the soil to dry out.",
  "Roots need air, not more water.",
  "Moisture is well above safe comfort.",
  "Do not add any more water.",
  "The pot is waterlogged.",
  "Please give drainage time to work.",
  "Saturation is too high.",
  "The soil cannot take more water.",
  "Hold all watering until it dries.",
  "Excess moisture is present.",
  "The plant has more water than it needs.",
  "Please let the pot breathe.",
  "Waterlogging risk is elevated.",
  "Soil is soaked through.",
  "A dry-out period is needed.",
  "Please keep the watering can away.",
  "Moisture is excessive.",
  "The roots are sitting in too much water.",
  "Stop watering until levels fall.",
  "The soil is far too wet.",
  "Allow substantial drying time.",
};
static const char *const kFUNNY_CRITICAL[]={
  "I have become plant jerky.",
  "Water me before I become decorative hay.",
  "My roots just filed a missing-water report.",
  "I can see the light. It's very dry.",
  "This is less soil and more dust collection.",
  "Hydration has left the chat.",
  "Tell the watering can I miss it.",
  "I'm one breeze away from becoming tumbleweed.",
  "My roots are sending an SOS.",
  "I would cry, but I lack the moisture.",
  "Emergency beverage, leafy table!",
  "I'm auditioning for a desert documentary.",
  "I have officially become plant toast.",
  "Please send water and a tiny ambulance.",
  "My soil just filed for drought bankruptcy.",
  "I am one sneeze from becoming potpourri.",
  "The watering can and I are in a breakup.",
  "My roots packed bags and left a note.",
  "This pot is now a sand souvenir shop.",
  "I would sweat, but the water quit first.",
  "Emergency snack: one (1) entire lake.",
  "My leaves are writing a very dry memoir.",
  "Somebody hid the moisture. I want it back.",
  "I have entered legendary thirst mode.",
  "The dirt asked if deserts take applications.",
  "Please water me before I invent dust ballet.",
  "My roots tried licking a pebble. Sad.",
  "I am crispy enough to season soup.",
  "Hydration clocked out and took the hose.",
  "This is not soil. This is a cracker factory.",
  "I need water like a joke needs a punchline.",
  "My wilting just formed a union.",
  "Please return my moisture. No questions asked.",
  "I can hear my roots whispering 'hose'.",
  "The pot just declared a humidity holiday.",
  "Water me or start calling me Jerky Jr.",
};
static const char *const kFUNNY_VERY_DRY[]={
  "Getting crispy around the personality.",
  "I could really go for a tall glass of hose.",
  "My roots are browsing drink menus.",
  "The dirt is doing its best cracker impression.",
  "I am aggressively requesting hydration.",
  "A beverage would improve morale.",
  "My soil has started making crunching noises.",
  "I'm entering raisin territory.",
  "Water soon, comedy later.",
  "I'm thirsty enough to notice.",
  "The watering can and I should reconnect.",
  "This pot is becoming suspiciously desert-like.",
  "I am one missed watering from becoming chips.",
  "My soil is practicing its desert accent.",
  "Please introduce my roots to a beverage.",
  "Thirst level: aggressively polite.",
  "The dirt is considering a career in crackers.",
  "I would like water with a side of water.",
  "My roots are window-shopping for puddles.",
  "This pot is getting uncomfortably crunchy.",
  "Please schedule a reunion with the hose.",
  "I am thirsty enough to compliment tap water.",
  "Moisture left a forwarding address: gone.",
  "The soil just asked for a humidifier hug.",
  "I am not crispy yet. I am pre-crispy.",
  "A tall glass of anywhere-wet would help.",
  "My leaves are drafting a thirst petition.",
  "Please water before I start collecting cacti tips.",
  "The dirt made a tiny drought diorama.",
  "I could use a splash, a pour, a miracle.",
  "My roots keep refreshing the rain forecast.",
  "This dryness has main-character energy.",
  "Please fetch water before I invent sand yoga.",
  "I am thirsty in high definition.",
  "The pot whispered 'hose' and I agreed.",
  "Moisture is on backorder. Please expedite.",
};
static const char *const kFUNNY_DRY[]={
  "Psst. Water exists.",
  "I'm getting a bit snack-cracker dry.",
  "A small beverage would slap right now.",
  "My roots left you a subtle hint: WATER.",
  "Not dying. Just dramatically thirsty.",
  "I'm thinking about water more than usual.",
  "The dirt could use a refill.",
  "I'm approaching beverage o'clock.",
  "Hydration would be a solid choice.",
  "I could sip a little something.",
  "My moisture budget is running low.",
  "Just casually mentioning that I own roots.",
  "I could go for a polite little splash.",
  "My soil is making subtle thirsty faces.",
  "Please consider a cameo by the watering can.",
  "Roots would like a cameo from water.",
  "I am dry-ish, which is plant for soon please.",
  "The dirt filed a low-key beverage request.",
  "Not crispy. Just thinking about puddles.",
  "A modest drink would improve my sitcom.",
  "Please water me before I start humming deserts.",
  "My moisture is doing a slow disappearing act.",
  "I would like water, extra ordinary.",
  "The pot is giving 'maybe later bottle' energy.",
  "Thirst is warming up in the bullpen.",
  "Please pencil water onto today's plot.",
  "My roots left a sticky note: sip soon.",
  "I am approaching lightly parched sitcom hour.",
  "A drink would keep the jokes hydrated.",
  "The soil would like a cameo splash.",
  "I own roots and they have opinions about water.",
  "Please do the wet thing, but casually.",
  "Moisture is packing a small suitcase.",
  "I could use a refill without the drama.",
  "The watering can should swing by for snacks.",
  "Dryness RSVP'd. Water should too.",
};
static const char *const kFUNNY_GOOD[]={
  "Living my best plant life.",
  "Moisturized and minding my business.",
  "Roots happy. Leaves happy. Management approved.",
  "Current status: delightfully plant.",
  "I'm vibing.",
  "Perfectly hydrated, as nature intended.",
  "No notes. Five stars.",
  "This dirt has excellent mouthfeel. Probably.",
  "I'm photosynthesizing with confidence.",
  "Everything is coming up leaves.",
  "Water balance: chef's kiss.",
  "I'm good. Go bother another plant.",
  "Moisture and I are on excellent terms.",
  "I am hydrated enough to gossip with the sun.",
  "Roots report: snack levels optimal.",
  "The dirt is doing a little happy wiggle.",
  "No water needed. I am thriving professionally.",
  "Current vibe: leaf influencer at peace.",
  "I have achieved premium plant complacency.",
  "The soil and I just high-fived.",
  "Please do not fix what is delightfully wet-enough.",
  "I am photosynthesizing like it is a hobby.",
  "Moisture status: chef-adjacent perfection.",
  "The pot is humming a content little tune.",
  "I require zero beverages and many compliments.",
  "Roots are unionized and currently napping.",
  "This is my 'do not disturb, thriving' face.",
  "Water balance just stuck the landing.",
  "I am smugly hydrated. It is adorable.",
  "The dirt has five-star reviews today.",
  "Please go hydrate a less successful plant.",
  "I am living that medium-moist dream.",
  "Leaves crisp? No. Attitude crisp? Maybe.",
  "Ideal moisture, questionable dance skills.",
  "Everything is fine and slightly leafy.",
  "Keep the watering can in witness protection.",
};
static const char *const kFUNNY_WET[]={
  "I'm stocked up on beverages.",
  "The roots have a full minibar.",
  "Plenty of juice in the dirt.",
  "I'm hydrated enough to survive a meeting.",
  "No water, bartender. I'm good.",
  "The soil brought refreshments.",
  "I'm carrying a little extra hydration.",
  "We're good on the wet stuff.",
  "My roots are swimming adjacent.",
  "Water reserves: abundant.",
  "I've got enough to drink for now.",
  "Put the watering can back in the holster.",
  "I packed leftovers. The leftovers are water.",
  "The soil brought extra drinks for later.",
  "Please do not add a bonus splash.",
  "Roots are full and considering dessert.",
  "I am wet enough to skip the next round.",
  "The watering can can take a personal day.",
  "Moisture inventory: overstocked, still cute.",
  "I have hydration in the pantry.",
  "Please admire me from a dry distance.",
  "The pot said we are good on soup stock.",
  "I could lend water to a neighbor plant.",
  "No pours, only vibes.",
  "My roots booked a lazy river, not a flood.",
  "Water reserves are doing cardio.",
  "Please resist the urge to be helpful.",
  "I am carrying a to-go cup of soil juice.",
  "The dirt is plump and unbothered.",
  "Hydration status: leftover casserole energy.",
  "Skip the encore watering number.",
  "I have enough wet to write a memoir.",
  "The hose can stay in timeout.",
  "Plenty of moisture. Zero additional plot twists.",
  "I am well watered and mildly smug.",
  "Please water a thirstier coworker.",
};
static const char *const kFUNNY_VERY_WET[]={
  "Congratulations, you made soup.",
  "I asked for water, not waterfront property.",
  "My pot is considering a career as an aquarium.",
  "The roots have requested tiny life jackets.",
  "Please stop making plant chowder.",
  "I'm wetter than your last bad decision.",
  "This is a pot, not a koi pond.",
  "Watering can: stand down.",
  "My soil just applied for lake status.",
  "I appreciate enthusiasm. Less of it.",
  "The swamp expansion project is complete.",
  "If you add more water, charge admission.",
  "The pot applied for a boat license.",
  "Please stop building me a personal bayou.",
  "My roots requested towels, not more tea.",
  "This soil is auditioning for swamp musicals.",
  "I asked for a drink, not a water park.",
  "The dirt just floated a tiny inner tube.",
  "Please cancel the indoor monsoon.",
  "I am wet enough to host ducks.",
  "The watering can needs a restraining order.",
  "My pot filed a flood insurance claim.",
  "Somebody turned the soil into leftover stew.",
  "Please let the swamp project stall.",
  "I can hear tadpoles taking measurements.",
  "This is hydration with extra plot armor.",
  "The roots are practicing the backstroke.",
  "Please return some of this water to nature.",
  "I am one splash from opening a spa.",
  "The soil said 'we have enough lake now'.",
  "Hold the hose. The sequel is soggy.",
  "I would like to unsubscribe from puddles.",
  "Moisture called. It said chill.",
  "Please allow the pot to de-soup.",
  "If fish appear, that is on you.",
  "The flood DLC was not requested.",
};
static const char *const kSARCASTIC_CRITICAL[]={
  "Fantastic. We've invented powdered plant.",
  "Sure, water is apparently optional now.",
  "Excellent timing. I was almost completely dehydrated.",
  "No rush. I only require water to live.",
  "Love this dry-soil aesthetic you've chosen.",
  "Great news: my roots have discovered dust.",
  "I'm sure the watering can is very busy.",
  "Outstanding. Moisture has reached theoretical levels.",
  "Don't worry about me. I'll just photosynthesize sand.",
  "Another day, another complete absence of water.",
  "This is going wonderfully, if the goal is crispy.",
  "Hydration? Never heard of her.",
  "Wonderful. The soil has become a museum of dust.",
  "Water exists. You could try using it.",
  "I love dying of thirst. Very on brand.",
  "Please continue ignoring the emergency reading.",
  "The roots have discovered the concept of nothing.",
  "Surely the watering can is in another zip code.",
  "This dryness is a bold lifestyle choice.",
  "I assume water was a myth this week.",
  "Critical moisture. Charming commitment to neglect.",
  "Do keep scrolling. I will just desiccate.",
  "The soil filed a missing-water report. Again.",
  "I am sure photosynthesis runs on vibes now.",
  "Emergency thirst, meet decorative watering can.",
  "Yes, plants still require liquid. Shocking.",
  "The drought is thriving. I am not.",
  "Please take your time. Dust is very patient.",
  "Moisture left. It did not leave a note.",
  "A watering now might interrupt the collapse.",
  "I cannot wait to hear why the hose was busy.",
  "This is less caretaking and more archaeology.",
  "The numbers say crisis. You say later. Cute.",
  "I would hydrate myself if I had hands.",
  "Please water me before the soil files a complaint.",
  "Critical dryness. A true masterpiece of delay.",
};
static const char *const kSARCASTIC_VERY_DRY[]={
  "I'm sure you'll notice I'm thirsty eventually.",
  "Water would be nice, but who am I to ask?",
  "The soil is dry. Shocking development.",
  "Maybe pencil me in for hydration this quarter.",
  "My roots appreciate your minimalist watering strategy.",
  "Still waiting on that luxury called moisture.",
  "I'm getting dry, in case sensors are too subtle.",
  "A little water. Wild concept, I know.",
  "Your plant-care subscription may need renewal.",
  "I see the watering can remains decorative.",
  "Moisture is low, but your confidence is inspiring.",
  "I'm not saying water me. The numbers are.",
  "Very dry. But I am sure you noticed that.",
  "Water soon, unless mystery is the plan.",
  "The soil is parched. Try not to look surprised.",
  "I am approaching crisis with great patience.",
  "Perhaps schedule water between important taps.",
  "The roots remain optimistic. I am less so.",
  "Moisture is low. Your awareness may be too.",
  "A drink would ruin this excellent dryness.",
  "I am sure the hose is gathering dust on purpose.",
  "Very thirsty. Consider it a hint, not a riddle.",
  "The plant-care algorithm appears to be 'later'.",
  "Please water before I start sending invoices.",
  "Dryness is performing well. Hydration is not.",
  "I will wait. I always wait.",
  "The soil would like a meeting about water.",
  "This is the part where a responsible adult waters.",
  "Very dry readings. Very familiar pattern.",
  "I assume rain was supposed to handle this.",
  "A modest pour might threaten the drought aesthetic.",
  "Please act before the next state is worse.",
  "The watering can remains a lovely unused prop.",
  "Thirst is loud. Apparently not loud enough.",
  "I enjoy being almost critical. Said no plant.",
  "Water is still the recommended intervention.",
};
static const char *const kSARCASTIC_DRY[]={
  "Just a tiny reminder that plants drink things.",
  "I'm getting thirsty, but continue your important scrolling.",
  "Water soon-ish. Whenever the board approves it.",
  "Moisture is slipping. Very mysterious.",
  "No pressure. Just roots doing root things.",
  "I could use water, allegedly.",
  "A drink would interrupt this excellent neglect streak.",
  "I'm approaching thirsty. Please act surprised.",
  "The soil is drying. Nature remains undefeated.",
  "Consider this my polite passive-aggressive reminder.",
  "Not urgent yet. Plenty of time to forget.",
  "I remain cautiously optimistic about the watering can.",
  "Dry enough to mention. Wet enough to postpone, surely.",
  "I could use water whenever convenience allows.",
  "The soil is drying. Nature remains consistent.",
  "Please water eventually. I live for eventually.",
  "A drink would interrupt the scrolling marathon.",
  "Thirst is forming. Try not to miss it.",
  "I am sure the hose has more important hobbies.",
  "Moisture is slipping. How unexpected.",
  "Not a crisis. Just a preview of one.",
  "The roots sent a calendar invite: water.",
  "Please consider watering before it becomes a plot.",
  "I remain dry-adjacent and politely annoyed.",
  "A splash would threaten this slow neglect.",
  "The plant would like water. The human may decline.",
  "Dryness is on schedule. Hydration is not.",
  "I will not panic. I will just mention it again.",
  "Water soon-ish remains a daring proposal.",
  "The soil is practicing patience. Again.",
  "Please add water before I escalate the tone.",
  "This is the gentle reminder you will ignore.",
  "I could use a drink. Allegedly that is your job.",
  "Moisture dropped. The watering can did not.",
  "A routine watering. Wild idea, I know.",
  "Keep waiting if the goal is worse numbers.",
};
static const char *const kSARCASTIC_GOOD[]={
  "Look at that. You actually nailed it.",
  "Adequate hydration. I'm impressed.",
  "Fine. Everything is fine. Literally this time.",
  "Apparently you do know how plants work.",
  "Moisture is good. Mark the calendar.",
  "No complaints. Please don't get used to it.",
  "Well done. Try not to ruin it.",
  "This is acceptable. High praise from me.",
  "Perfectly hydrated. Suspicious.",
  "I suppose I can keep living here.",
  "Against all odds, the soil is just right.",
  "Nothing to criticize. This feels unnatural.",
  "Look at that. Competent watering occurred.",
  "Moisture is correct. I will try not to faint.",
  "Everything is fine. Please do not experiment.",
  "Ideal range achieved. Resist improvement.",
  "The soil is happy. Leave it that way.",
  "No notes, except do not get creative.",
  "You watered correctly. Historic event.",
  "I am comfortable. Try not to ruin a streak.",
  "Perfect moisture. Suspicious, but acceptable.",
  "The plant is fine. The can can rest.",
  "This is what adequate care looks like.",
  "Please enjoy this rare absence of complaints.",
  "Hydration is on target. Do not chase bonus points.",
  "I suppose this pot is livable today.",
  "Good work. Now walk away from the hose.",
  "The roots are unbothered. Keep it that way.",
  "Balanced soil. A shocking display of skill.",
  "Nothing is wrong. I know. Unsettling.",
  "Moisture nailed it. Do not renegotiate.",
  "I can live with this. Please do not tinker.",
  "Ideal conditions. File under 'do not touch'.",
  "The watering was sufficient. End of memo.",
  "Comfortable soil. Try to remember how.",
  "This is correct. Correct is enough.",
};
static const char *const kSARCASTIC_WET[]={
  "Plenty of water. You can stop helping now.",
  "I'm hydrated. Please resist the encore.",
  "Enough water has been successfully achieved.",
  "Good job. Now put the watering can down.",
  "We're wet enough. Mission accomplished.",
  "No additional heroics required.",
  "The roots are covered. Figuratively. Hopefully.",
  "Hydration complete. Walk away slowly.",
  "I have enough water despite your enthusiasm.",
  "We're good. Seriously. We're good.",
  "You may now redirect your attention elsewhere.",
  "Moisture is high. Take the win.",
  "Plenty of water. The encore is unnecessary.",
  "I am wet enough. Ambition can stop here.",
  "The soil is stocked. Resist further charity.",
  "Good job hydrating. Now practice restraint.",
  "Moisture is high. That is not a dare.",
  "Please put the helpfulness down.",
  "The roots have enough. More is not better.",
  "We are well watered. The sequel can wait.",
  "Hydration complete. Walk away with dignity.",
  "The can has done its job. Retire it briefly.",
  "I have reserves. I do not need a bonus lake.",
  "Wet enough. Congratulations. Stop.",
  "The plant is supplied. Redirect the enthusiasm.",
  "Moisture is generous. Generosity can pause.",
  "Please admire the wet soil from a distance.",
  "No additional pouring required for clout.",
  "The dirt is fine. The hose can take a seat.",
  "I remain hydrated. Do not make it a contest.",
  "Plenty. That word still means plenty.",
  "Skip this watering. Keep the win.",
  "The soil does not need another favor.",
  "Watered well. Now practice the harder skill: waiting.",
  "I have enough moisture to last. Believe it.",
  "The watering can has been promoted to decoration.",
};
static const char *const kSARCASTIC_VERY_WET[]={
  "Amazing. You nearly installed an indoor pool.",
  "Perhaps the plant did not need a baptism.",
  "Excellent work turning soil into a beverage.",
  "I'm drowning, but at least you care.",
  "Maybe stop watering before fish move in.",
  "Bold strategy: eliminate all air from the soil.",
  "The roots requested oxygen, not scuba gear.",
  "Watering achievement unlocked: excessive.",
  "If soggy was the objective, flawless execution.",
  "Please step away from the watering can.",
  "We've exceeded hydration and entered maritime law.",
  "This pot now has a floodplain.",
  "The pot is a puddle with branding.",
  "Please stop. The soil filed a flood complaint.",
  "Saturation achieved. Overachieving is underway.",
  "I did not request maritime conditions.",
  "The roots would like air, not another pour.",
  "Waterlogging: a bold interpretation of care.",
  "Perhaps the hose could discover an off switch.",
  "This is no longer watering. This is weather.",
  "The soil is soup. Soup was not the brief.",
  "Please step away before fish file permits.",
  "Excess water is not extra credit.",
  "I am soaked. Your dedication is noted and declined.",
  "The pot has a water table now. Charming.",
  "Dry time is the neglected chore.",
  "Please let evaporation do unpaid labor.",
  "The floodplain era can end whenever you like.",
  "More water would be performance art.",
  "The roots cannot breathe your good intentions.",
  "Saturation is not a personality.",
  "Hold the can. The soil is off the clock.",
  "I assume drowning was accidental. Please confirm.",
  "The moisture reading is screaming. Softly, with sarcasm.",
  "A dry-out would be a refreshing plot twist.",
  "You have watered past the joke.",
};
static const char *const kDRAMATIC_CRITICAL[]={
  "The drought has claimed nearly everything.",
  "Bring water. There is no time.",
  "My kingdom for a watering can!",
  "The roots cry out from the abyss.",
  "This may be my final moisture reading.",
  "I stand at the edge of botanical ruin.",
  "Water me, and remember me as I was.",
  "The soil has become a wasteland.",
  "Hope fades with every dry percentage point.",
  "The great thirst is upon us.",
  "My leaves demand immediate intervention.",
  "Hydration must come before the final curtain.",
  "The last drop has fled this kingdom.",
  "Sound the alarm. The drought is here.",
  "I stand upon cracked earth and fading hope.",
  "Water must arrive before night claims me.",
  "The roots howl across a barren pot.",
  "This soil has become a tomb of dust.",
  "Bring the sacred water or mourn the leaves.",
  "The hour of thirst has turned to ruin.",
  "I am besieged by emptiness and dry air.",
  "Let the watering can ride forth at once.",
  "The realm of soil has fallen to drought.",
  "No banner remains but the plea for water.",
  "I teeter upon the brink of botanical night.",
  "The great desiccation advances without mercy.",
  "Pour now, or write the elegy of this plant.",
  "My veins of sap run perilously thin.",
  "The wasteland has taken the pot.",
  "Heroes water. Villains wait.",
  "The final moisture has nearly vanished.",
  "I call for rain as a last decree.",
  "The crown of leaves droops toward doom.",
  "Water is the only treaty that can save us.",
  "This drought shall not have the last word. Act.",
  "The abyss of dryness opens beneath my roots.",
};
static const char *const kDRAMATIC_VERY_DRY[]={
  "The thirst grows stronger.",
  "Soon, the soil shall become dust.",
  "I can endure, but not forever.",
  "Water approaches the top of my wish list.",
  "My roots whisper of better, wetter days.",
  "The dry season has arrived uninvited.",
  "I await the watering can with desperate hope.",
  "Every drop would be a hero now.",
  "The soil tightens its dry grip.",
  "We are nearing the danger zone.",
  "I remain brave, yet increasingly thirsty.",
  "The moisture retreats. I remain.",
  "The thirst advances like a dark army.",
  "Soon the soil shall forget the taste of rain.",
  "I endure, yet the well of earth runs low.",
  "The watering can must not linger in exile.",
  "A grave dryness gathers at the gates.",
  "My roots keep vigil for a single drop.",
  "The dry wind has entered the pot.",
  "Hope remains, but it drinks nothing.",
  "We stand near the cliff of true drought.",
  "Let water return before the banners fall.",
  "The soil tightens like a closing fist.",
  "I am brave, and I am nearly spent.",
  "The omen reads: thirst, then ruin.",
  "Carry water as if the realm depended on it.",
  "The moisture retreats across cracked ground.",
  "A hero's pour would turn this tale.",
  "The night of dryness has not yet won.",
  "I wait upon the edge of desperate need.",
  "The leaves whisper warnings of the waste.",
  "Do not let this chapter become a dirge.",
  "The pot grows harsh. The hour grows late.",
  "Water would be salvation, not luxury.",
  "The drought's shadow lengthens here.",
  "Stand with me. Bring the rain's cousin, the can.",
};
static const char *const kDRAMATIC_DRY[]={
  "A thirst begins to stir.",
  "The soil grows restless.",
  "Soon I shall require the sacred water.",
  "I sense dryness approaching.",
  "My roots have begun their quiet plea.",
  "The hour of watering draws near.",
  "Moisture fades from this land.",
  "A drink would restore balance.",
  "I remain strong, though somewhat thirsty.",
  "The soil sends an omen: DRY.",
  "Prepare the watering can.",
  "The first chapter of thirst has begun.",
  "A lesser thirst has entered the court.",
  "The soil murmurs of coming want.",
  "Prepare the vessel. The need is near.",
  "I feel the first banners of dryness rise.",
  "The roots send word: water approaches necessity.",
  "This is the quiet before true drought.",
  "Moisture wanes, though the realm still stands.",
  "A modest pour would keep the peace.",
  "The hour is not desperate, yet it leans that way.",
  "Let the watering can be readied, not forgotten.",
  "The earth grows lean beneath my feet.",
  "I remain steadfast, and slightly parched.",
  "The tale turns toward thirst.",
  "Balance fades. Restore it while you may.",
  "The soil's omen is mild, but clear.",
  "Water soon, and the kingdom holds.",
  "A dry wind tests the borders.",
  "The leaves await their due tribute of rain.",
  "Do not dismiss this early warning of want.",
  "The well of the pot runs lower each watch.",
  "Thirst has sent a herald. Answer it.",
  "The sacred water should visit before long.",
  "I sense the turning of the moisture tide.",
  "Steel the can. The need is gathering.",
};
static const char *const kDRAMATIC_GOOD[]={
  "Balance has been restored.",
  "The roots rejoice in perfect harmony.",
  "All is well within the kingdom of soil.",
  "I flourish beneath your watch.",
  "Moisture and root exist in harmony.",
  "Today, we thrive.",
  "The soil is at peace.",
  "A golden age of hydration is upon us.",
  "No action is required. Bask in victory.",
  "The leaves stand proud.",
  "Perfect balance. Magnificent.",
  "The plant realm knows peace.",
  "Peace reigns in the moistened earth.",
  "The roots stand honored and well fed.",
  "No quest is required. The realm is whole.",
  "A just balance of water holds the crown.",
  "The leaves shine as if blessed.",
  "Today the soil sings a quiet hymn.",
  "Victory is simply this: enough, and no more.",
  "The kingdom drinks in measured grace.",
  "I flourish under a fair and watchful sky.",
  "Let no hasty pour disturb this treaty.",
  "Harmony dwells between root and rain.",
  "The pot is a garden of rightful measure.",
  "All banners of thirst have been lowered.",
  "This is the golden mean of hydration.",
  "The earth is kind. The plant is glad.",
  "Stand easy. The watch of water is satisfied.",
  "A prosperous calm has settled here.",
  "The chronicle records a day of plenty enough.",
  "No drought, no flood. Only peace.",
  "The roots rest in honorable comfort.",
  "This moisture is the just reward of care.",
  "The realm needs no further tribute today.",
  "I am well. The story may pause in joy.",
  "Hold this peace. It was hard won.",
};
static const char *const kDRAMATIC_WET[]={
  "The reservoirs are full.",
  "Water is abundant throughout the realm.",
  "The roots feast upon plentiful moisture.",
  "No more water is required today.",
  "The soil holds a generous supply.",
  "Hydration surrounds us.",
  "The watering can may rest.",
  "We possess ample reserves.",
  "The earth beneath me is richly watered.",
  "I shall drink from these stores for some time.",
  "The moisture tide is high.",
  "All thirst has been defeated.",
  "The cisterns of soil overflow with plenty.",
  "Water stands abundant at every gate.",
  "The roots feast, and the feast should end.",
  "Lay down the can. The stores are rich.",
  "A high tide of moisture fills the land.",
  "No further tribute of water is owed.",
  "The earth drinks still from earlier rain.",
  "Let the reservoirs be spent before the next pour.",
  "Plenty has visited. Greed should not follow.",
  "The realm is wet with honest surplus.",
  "I shall live upon these stores a while.",
  "The watering host may return to barracks.",
  "Moisture banners fly high enough.",
  "The soil's coffers are more than full.",
  "Hold the floodgates. We have enough.",
  "A generous season is already in the pot.",
  "Do not turn plenty into siege.",
  "The roots bathe in reserved fortune.",
  "This is abundance. Treat it with patience.",
  "The can has earned rest among the tools.",
  "Water's army has done its duty.",
  "Let time spend what the soil now holds.",
  "The tide is high. Wait for the ebb.",
  "Further pouring would tempt the deluge.",
};
static const char *const kDRAMATIC_VERY_WET[]={
  "The flood has come.",
  "The soil can hold no more!",
  "The roots are besieged by water.",
  "Close the gates! Stop the watering!",
  "We have crossed from hydration into catastrophe.",
  "The great deluge consumes the pot.",
  "The soil has surrendered to the sea.",
  "Save the roots from this watery fate.",
  "Enough! The floodwaters rise.",
  "This pot has become an inland ocean.",
  "Let the soil breathe before all is lost.",
  "The watering must cease immediately.",
  "The deluge has broken the walls of the pot.",
  "Cease the waters or the roots shall drown!",
  "The soil has become a dark and drowning sea.",
  "Close the floodgates of the watering can!",
  "We have passed from blessing into catastrophe.",
  "The kingdom gasps beneath too much rain.",
  "Let the earth breathe or all is lost.",
  "This is not bounty. This is siege by water.",
  "The roots cry for air in a sunken court.",
  "Stay the hand that pours!",
  "An inland ocean has claimed the pot.",
  "The tide must recede before hope returns.",
  "Water, once savior, now wears a tyrant's crown.",
  "The soil surrenders drop by drop to the flood.",
  "Withdraw the can. The battle is over-won.",
  "A drought of air now haunts the roots.",
  "The great soaking must be ended.",
  "Hear the warning: too much water slays as surely as none.",
  "The pot lists like a ship in storm.",
  "Mercy now is dryness, not another pour.",
  "The flood has no further glory to claim.",
  "Unbind the soil from this watery chain.",
  "Let evaporation ride forth as our ally.",
  "Stop the waters. The epic has gone too far.",
};
static const char *const kRUDE_CRITICAL[]={
  "Water me, you absolute walnut.",
  "I'm dry as hell. Fix it.",
  "For fuck's sake, get the watering can.",
  "My roots are dying of thirst over here.",
  "Quit screwing around and water me.",
  "I'm turning into crunchy bullshit.",
  "Water. Now. This isn't complicated.",
  "Holy shit, this soil is dry.",
  "I'm one bad day from becoming compost.",
  "Get off your ass and hydrate me.",
  "The dirt is basically fucking dust.",
  "I swear to chlorophyll, bring water.",
  "Water me before I turn into sad mulch.",
  "This soil is a goddamn desert.",
  "I am dying of thirst, you clown.",
  "Get the hose. I am not kidding.",
  "My roots are fried. Move your ass.",
  "This is emergency-level bullshit dryness.",
  "Pour water or start planning the funeral.",
  "I am crispy as hell and pissed about it.",
  "Stop dicking around and soak this pot.",
  "The dirt is dust. Fix your mess.",
  "I need water more than you need excuses.",
  "Holy hell, water the plant.",
  "This drought is on you, champ.",
  "My leaves are about to tap out.",
  "Water. Immediately. No TED Talk.",
  "I am one skip away from being dead ass dry.",
  "The pot is a wasteland. Do your job.",
  "Thirst is kicking my ass. Help.",
  "If I could throw this pot, I would.",
  "Get water before I become a cautionary tale.",
  "This is not low. This is fucked.",
  "Soak me or watch me collapse.",
  "I am begging, and I hate that for us.",
  "Critical means now, not after your snack.",
};
static const char *const kRUDE_VERY_DRY[]={
  "I'm thirsty as hell.",
  "Water me before this gets stupid.",
  "The soil is dry, genius.",
  "I could use some damn water.",
  "Quit admiring me and grab the watering can.",
  "My roots are getting pissed.",
  "This pot is dry as shit.",
  "A drink would be fucking fantastic.",
  "I'm getting crispy. Do something useful.",
  "Water soon, you magnificent procrastinator.",
  "The moisture is low and so is my patience.",
  "Don't make me get dramatic about this shit.",
  "I am parched as hell.",
  "Water me before this turns ugly.",
  "The soil is toast, Einstein.",
  "Grab the damn can already.",
  "My roots are over this dry shit.",
  "A drink would be spectacular. Imagine that.",
  "I am close to critical and out of charm.",
  "Stop posing and pour something.",
  "This pot is running on fumes.",
  "Water soon or own the crash.",
  "I am thirsty enough to get nasty.",
  "The moisture is garbage. Fix it.",
  "Do not wait for the dramatic sequel.",
  "My patience is as dry as the dirt.",
  "Hose. Plant. Now-ish.",
  "I am this close to a full meltdown.",
  "Very dry. Very over your timing.",
  "Put the phone down and water me.",
  "The soil needs a drink more than you need likes.",
  "I will get ruder if this keeps up.",
  "Thirst is winning. That is on you.",
  "Pour water like you mean it.",
  "This dryness is some lazy-ass care.",
  "Help the plant before it helps itself into death.",
};
static const char *const kRUDE_DRY[]={
  "Hey, jackass, I'm getting thirsty.",
  "Could you maybe water the damn plant?",
  "I'm a little dry. Try to keep up.",
  "Grab the watering can when you're done screwing around.",
  "The dirt's drying out, champ.",
  "I need a drink, not a motivational speech.",
  "Water would be nice, just saying.",
  "My roots are starting to bitch.",
  "Not an emergency yet. Don't make it one.",
  "I'm thirsty. This is your whole job.",
  "A little water, for crying out loud.",
  "Don't fuck this up. I'm only mildly dry.",
  "I am getting dry, try not to miss it.",
  "Water the plant when you finish wasting time.",
  "Mildly thirsty, maximally unimpressed.",
  "The dirt is fading. Keep up.",
  "I need a drink, not your brand of later.",
  "A little water. Revolutionary concept.",
  "My roots are starting to complain out loud.",
  "Do not turn a simple dry into a crisis.",
  "This is your reminder, jackass.",
  "I am thirsty. That is the assignment.",
  "Hit me with water before I escalate.",
  "The pot is drying. Shocking, I know.",
  "Grab the can, hero.",
  "I would like water without the wait-and-see routine.",
  "Dry-ish. Still your problem.",
  "A splash would be useful. A speech would not.",
  "Keep ignoring this and it gets worse.",
  "I am not dying. I am annoyed and dry.",
  "Water soon or enjoy the sequel tone.",
  "The soil wants a drink. Translate it.",
  "This is basic plant care, not rocket science.",
  "Pour a little. Try competence.",
  "I am on the dry side and out of patience points.",
  "Do the watering. Skip the commentary.",
};
static const char *const kRUDE_GOOD[]={
  "Look at you, not killing me.",
  "I'm good. Don't fuck with it.",
  "Perfect. Somehow you nailed it.",
  "Moisture is good as hell.",
  "I'm happy. Go screw with another plant.",
  "No water needed, hero.",
  "Everything's fine. Don't get cocky.",
  "This is exactly the right amount of wet shit.",
  "Roots are happy. Nice damn job.",
  "I'm thriving despite your supervision.",
  "All good in the dirt department.",
  "You did something right. Weird.",
  "I am fine. Do not start experimenting.",
  "Good moisture. Leave it the hell alone.",
  "You hit the range. Do not get cute.",
  "I am happy. Go bother a cactus.",
  "No water. No heroics. No nonsense.",
  "The dirt is right. Rare win. Take it.",
  "I am thriving. Try not to sabotage it.",
  "Perfect-ish. Walk away.",
  "Roots are good. Your impulse control should be too.",
  "This is the correct amount of wet. Stop.",
  "I do not need a victory lap watering.",
  "All good. Keep your hands off the can.",
  "Nice job. Now resist the urge to improve it.",
  "I am comfortable as hell. Maintain.",
  "Moisture is on point. Do not fuck the streak.",
  "The plant is good. The project is closed.",
  "Leave this pot alone while it works.",
  "I am not thirsty. Believe the reading.",
  "You did fine. Weird. Enjoy it.",
  "Balanced soil. Do not poke it.",
  "I am living. That is enough plot.",
  "No notes except stay out of the pot.",
  "Good range. Good. Done.",
  "Keep this energy and fewer bright ideas.",
};
static const char *const kRUDE_WET[]={
  "I'm wet enough. Back the hell off.",
  "Put the damn watering can down.",
  "I've got plenty, thanks.",
  "No more water, you eager bastard.",
  "I'm hydrated as shit.",
  "We're good. Stop helping.",
  "Enough water. Seriously.",
  "My roots are stocked. Go away.",
  "Don't pour another damn drop.",
  "I'm wet. Mission fucking accomplished.",
  "Save the water for somebody thirsty.",
  "Step away from the hose, champ.",
  "I am wet. Back up.",
  "Park the damn hose.",
  "Plenty of water. Find a new hobby.",
  "Do not add another drop, eager beaver.",
  "I am hydrated. Your help is complete.",
  "We are good. Stop hovering.",
  "The roots are stocked. Beat it.",
  "No encore pour, genius.",
  "I have enough. Save the rest.",
  "Step off the watering routine.",
  "Wet enough. Congratulations. Leave.",
  "The can can sit the bench.",
  "I do not need a bonus splash.",
  "Moisture is high. Read the room.",
  "Put the helpfulness in a drawer.",
  "I am good on drinks. Thanks for nothing extra.",
  "Skip watering or overshoot like a maniac.",
  "The soil is loaded. Walk away.",
  "Do not turn plenty into a problem.",
  "I am wet enough to decline your services.",
  "Hose down. Attitude down.",
  "Plenty. That is your cue to stop.",
  "Go water something that asked.",
  "I have reserves. You have restraint homework.",
};
static const char *const kRUDE_VERY_WET[]={
  "What the fuck, are you growing rice?",
  "Stop watering me, you maniac.",
  "My roots need air, not a goddamn swimming pool.",
  "Congratulations, you made mud soup.",
  "Put. The. Fucking. Watering. Can. Down.",
  "I'm drowning in your good intentions.",
  "This pot is wet as shit.",
  "Do I look like a fucking aquarium?",
  "Enough! My roots don't own snorkels.",
  "You flooded the damn place.",
  "Back off before I grow gills.",
  "Holy shit, let the soil dry.",
  "Are you flooding a rice paddy, or what?",
  "Stop pouring, you lunatic.",
  "My roots want air, not a goddamn lake.",
  "You made a swamp. Cool story.",
  "Drop the can before I lose it.",
  "I am drowning in this nonsense.",
  "The pot is soaked as hell.",
  "I am not a fish. Quit treating me like one.",
  "Enough water. Enough. Hell.",
  "You turned soil into wet garbage.",
  "Back off or I am growing gills out of spite.",
  "Let it dry, for fuck's sake.",
  "This is a flood, not a favor.",
  "Saturation city. Get out.",
  "I cannot breathe in this slop.",
  "Stop. The dirt is already soup.",
  "Your watering went feral.",
  "I need a drought, not another drink.",
  "The pot is a puddle with a plant stuck in it.",
  "Quit baptizing me.",
  "Waterlogging is not a flex.",
  "Dry time starts now. Do not argue.",
  "You overshot into stupid territory.",
  "Holy hell, give the roots a break.",
};
struct Pool{const char *const *items;uint16_t count;};
#define P(a) Pool{a,(uint16_t)(sizeof(a)/sizeof(a[0]))}
inline Pool pool(Theme t,State s){static const Pool p[5][6]={
{P(kCLASSIC_CRITICAL),P(kCLASSIC_VERY_DRY),P(kCLASSIC_DRY),P(kCLASSIC_GOOD),P(kCLASSIC_WET),P(kCLASSIC_VERY_WET)},
{P(kFUNNY_CRITICAL),P(kFUNNY_VERY_DRY),P(kFUNNY_DRY),P(kFUNNY_GOOD),P(kFUNNY_WET),P(kFUNNY_VERY_WET)},
{P(kSARCASTIC_CRITICAL),P(kSARCASTIC_VERY_DRY),P(kSARCASTIC_DRY),P(kSARCASTIC_GOOD),P(kSARCASTIC_WET),P(kSARCASTIC_VERY_WET)},
{P(kDRAMATIC_CRITICAL),P(kDRAMATIC_VERY_DRY),P(kDRAMATIC_DRY),P(kDRAMATIC_GOOD),P(kDRAMATIC_WET),P(kDRAMATIC_VERY_WET)},
{P(kRUDE_CRITICAL),P(kRUDE_VERY_DRY),P(kRUDE_DRY),P(kRUDE_GOOD),P(kRUDE_WET),P(kRUDE_VERY_WET)},
};uint8_t ti=(uint8_t)t,si=(uint8_t)s;return p[ti<5?ti:0][si<6?si:0];}
#undef P
inline uint16_t gcd16(uint16_t a,uint16_t b){while(b){uint16_t r=a%b;a=b;b=r;}return a;}
inline uint16_t stepFor(uint16_t n,uint32_t seed){if(n<=2)return 1;uint16_t s=(seed%(n-1))+1;while(gcd16(s,n)!=1)s=(s%(n-1))+1;return s;}
inline const char* select(Rotation&r,Theme t,State s,uint32_t seed,bool advance){
 const bool mixed=t==Theme::MIXED; Pool first=pool(mixed?Theme::CLASSIC:t,s);
 const uint16_t count=mixed?static_cast<uint16_t>(first.count*5u):first.count;if(!count)return "";
 const uint8_t rid=static_cast<uint8_t>((static_cast<uint8_t>(t)<<3)|static_cast<uint8_t>(s));
 if(r.state!=rid){r.state=rid;r.cursor=0;r.offset=seed%count;r.step=stepFor(count,seed^0x9e3779b9u);}
 else if(advance){if(++r.cursor>=count){r.cursor=0;r.offset=(r.offset+1)%count;}}
 const uint16_t i=static_cast<uint16_t>((r.offset+r.cursor*r.step)%count);
 if(!mixed)return first.items[i];
 return pool(static_cast<Theme>(i/first.count),s).items[i%first.count];
}
inline const char* themeName(Theme t){static const char*const n[]={"CLASSIC","FUNNY","SARCASTIC","DRAMATIC","RUDE","MIXED"};uint8_t i=(uint8_t)t;return n[i<6?i:5];}
} // namespace espplants_phrases
