#pragma once
#include <Arduino.h>
namespace espplants_phrases {
enum class Theme:uint8_t { CLASSIC=0,FUNNY=1,SARCASTIC=2,DRAMATIC=3,RUDE=4,MIXED=5 };
enum class State:uint8_t { CRITICAL=0,VERY_DRY=1,DRY=2,GOOD=3,WET=4,VERY_WET=5 };
struct Rotation { uint8_t state=0xff; uint16_t cursor=0,step=1,offset=0; };
inline State stateFor(uint8_t m,bool warning){ if(warning||m<=10)return State::CRITICAL;if(m<=20)return State::VERY_DRY;if(m<=40)return State::DRY;if(m<=70)return State::GOOD;if(m<=85)return State::WET;return State::VERY_WET; }
static const char *const kCLASSIC_CRITICAL[]={
  "Emergency drink required.",
  "Soil moisture is critically low.",
  "I need water now.",
  "Please water me as soon as possible.",
  "My soil is extremely dry.",
  "Critical moisture level reached.",
  "I'm running out of water.",
  "This plant needs immediate attention.",
  "Water level: critically low.",
  "I'm seriously thirsty.",
  "Please don't make me wait.",
  "A good soak would help right now.",
};
static const char *const kCLASSIC_VERY_DRY[]={
  "I'm very thirsty.",
  "My soil is getting seriously dry.",
  "Water would be appreciated soon.",
  "I'm getting parched.",
  "It's definitely time for a drink.",
  "Moisture is well below comfortable.",
  "I'm asking nicely: water, please.",
  "Things are getting dry down here.",
  "A drink should be on the schedule.",
  "I'm not critical yet, but close.",
  "My roots could use some water.",
  "Please check my soil soon.",
};
static const char *const kCLASSIC_DRY[]={
  "Getting a little thirsty.",
  "I could use a drink.",
  "My soil is starting to dry out.",
  "Water me when you get a chance.",
  "I'm getting toward the dry side.",
  "A little water would be nice.",
  "Moisture is dropping.",
  "I'm ready for my next drink.",
  "Not desperate, just thirsty.",
  "My roots are asking for a refill.",
  "It's almost watering time.",
  "Keep an eye on my moisture.",
};
static const char *const kCLASSIC_GOOD[]={
  "Doing good.",
  "Moisture feels just right.",
  "I'm happy right here.",
  "No water needed right now.",
  "Everything is comfortable.",
  "Roots are happy.",
  "I'm in the sweet spot.",
  "All good down here.",
  "Moisture level looks great.",
  "I'm doing just fine.",
  "This is a comfortable amount of water.",
  "Nothing needed from you right now.",
};
static const char *const kCLASSIC_WET[]={
  "Nice and moist.",
  "I've got plenty of water.",
  "No refill needed.",
  "I'm well watered.",
  "Moisture is on the high side.",
  "I'm good for a while.",
  "Plenty of water down here.",
  "You can skip watering me.",
  "My soil is comfortably wet.",
  "Water supply looks generous.",
  "I'm definitely not thirsty.",
  "Let me use what I have first.",
};
static const char *const kCLASSIC_VERY_WET[]={
  "I'm very wet right now.",
  "Please hold off on watering.",
  "My soil is saturated.",
  "Definitely no more water yet.",
  "I have more than enough water.",
  "Let me dry out a little.",
  "The soil is extremely wet.",
  "Watering can take a break.",
  "I'm full, thanks.",
  "Roots have plenty to work with.",
  "No water needed for quite a while.",
  "Please give the soil time to dry.",
};
static const char *const kFUNNY_CRITICAL[]={
  "I have become plant jerky.",
  "Water me before I become decorative hay.",
  "My roots just filed a missing-water report.",
  "I can see the light. It's very dry.",
  "This is less soil and more dust collection.",
  "Hydration has left the chat.",
  "Tell the watering can I miss it.",
  "I'm one breeze away from becoming tumbleweed.",
  "My roots are sending an SOS.",
  "I would cry, but I lack the moisture.",
  "Emergency beverage, leafy table!",
  "I'm auditioning for a desert documentary.",
};
static const char *const kFUNNY_VERY_DRY[]={
  "Getting crispy around the personality.",
  "I could really go for a tall glass of hose.",
  "My roots are browsing drink menus.",
  "The dirt is doing its best cracker impression.",
  "I am aggressively requesting hydration.",
  "A beverage would improve morale.",
  "My soil has started making crunching noises.",
  "I'm entering raisin territory.",
  "Water soon, comedy later.",
  "I'm thirsty enough to notice.",
  "The watering can and I should reconnect.",
  "This pot is becoming suspiciously desert-like.",
};
static const char *const kFUNNY_DRY[]={
  "Psst. Water exists.",
  "I'm getting a bit snack-cracker dry.",
  "A small beverage would slap right now.",
  "My roots left you a subtle hint: WATER.",
  "Not dying. Just dramatically thirsty.",
  "I'm thinking about water more than usual.",
  "The dirt could use a refill.",
  "I'm approaching beverage o'clock.",
  "Hydration would be a solid choice.",
  "I could sip a little something.",
  "My moisture budget is running low.",
  "Just casually mentioning that I own roots.",
};
static const char *const kFUNNY_GOOD[]={
  "Living my best plant life.",
  "Moisturized and minding my business.",
  "Roots happy. Leaves happy. Management approved.",
  "Current status: delightfully plant.",
  "I'm vibing.",
  "Perfectly hydrated, as nature intended.",
  "No notes. Five stars.",
  "This dirt has excellent mouthfeel. Probably.",
  "I'm photosynthesizing with confidence.",
  "Everything is coming up leaves.",
  "Water balance: chef's kiss.",
  "I'm good. Go bother another plant.",
};
static const char *const kFUNNY_WET[]={
  "I'm stocked up on beverages.",
  "The roots have a full minibar.",
  "Plenty of juice in the dirt.",
  "I'm hydrated enough to survive a meeting.",
  "No water, bartender. I'm good.",
  "The soil brought refreshments.",
  "I'm carrying a little extra hydration.",
  "We're good on the wet stuff.",
  "My roots are swimming adjacent.",
  "Water reserves: abundant.",
  "I've got enough to drink for now.",
  "Put the watering can back in the holster.",
};
static const char *const kFUNNY_VERY_WET[]={
  "Congratulations, you made soup.",
  "I asked for water, not waterfront property.",
  "My pot is considering a career as an aquarium.",
  "The roots have requested tiny life jackets.",
  "Please stop making plant chowder.",
  "I'm wetter than your last bad decision.",
  "This is a pot, not a koi pond.",
  "Watering can: stand down.",
  "My soil just applied for lake status.",
  "I appreciate enthusiasm. Less of it.",
  "The swamp expansion project is complete.",
  "If you add more water, charge admission.",
};
static const char *const kSARCASTIC_CRITICAL[]={
  "Fantastic. We've invented powdered plant.",
  "Sure, water is apparently optional now.",
  "Excellent timing. I was almost completely dehydrated.",
  "No rush. I only require water to live.",
  "Love this dry-soil aesthetic you've chosen.",
  "Great news: my roots have discovered dust.",
  "I'm sure the watering can is very busy.",
  "Outstanding. Moisture has reached theoretical levels.",
  "Don't worry about me. I'll just photosynthesize sand.",
  "Another day, another complete absence of water.",
  "This is going wonderfully, if the goal is crispy.",
  "Hydration? Never heard of her.",
};
static const char *const kSARCASTIC_VERY_DRY[]={
  "I'm sure you'll notice I'm thirsty eventually.",
  "Water would be nice, but who am I to ask?",
  "The soil is dry. Shocking development.",
  "Maybe pencil me in for hydration this quarter.",
  "My roots appreciate your minimalist watering strategy.",
  "Still waiting on that luxury called moisture.",
  "I'm getting dry, in case sensors are too subtle.",
  "A little water. Wild concept, I know.",
  "Your plant-care subscription may need renewal.",
  "I see the watering can remains decorative.",
  "Moisture is low, but your confidence is inspiring.",
  "I'm not saying water me. The numbers are.",
};
static const char *const kSARCASTIC_DRY[]={
  "Just a tiny reminder that plants drink things.",
  "I'm getting thirsty, but continue your important scrolling.",
  "Water soon-ish. Whenever the board approves it.",
  "Moisture is slipping. Very mysterious.",
  "No pressure. Just roots doing root things.",
  "I could use water, allegedly.",
  "A drink would interrupt this excellent neglect streak.",
  "I'm approaching thirsty. Please act surprised.",
  "The soil is drying. Nature remains undefeated.",
  "Consider this my polite passive-aggressive reminder.",
  "Not urgent yet. Plenty of time to forget.",
  "I remain cautiously optimistic about the watering can.",
};
static const char *const kSARCASTIC_GOOD[]={
  "Look at that. You actually nailed it.",
  "Adequate hydration. I'm impressed.",
  "Fine. Everything is fine. Literally this time.",
  "Apparently you do know how plants work.",
  "Moisture is good. Mark the calendar.",
  "No complaints. Please don't get used to it.",
  "Well done. Try not to ruin it.",
  "This is acceptable. High praise from me.",
  "Perfectly hydrated. Suspicious.",
  "I suppose I can keep living here.",
  "Against all odds, the soil is just right.",
  "Nothing to criticize. This feels unnatural.",
};
static const char *const kSARCASTIC_WET[]={
  "Plenty of water. You can stop helping now.",
  "I'm hydrated. Please resist the encore.",
  "Enough water has been successfully achieved.",
  "Good job. Now put the watering can down.",
  "We're wet enough. Mission accomplished.",
  "No additional heroics required.",
  "The roots are covered. Figuratively. Hopefully.",
  "Hydration complete. Walk away slowly.",
  "I have enough water despite your enthusiasm.",
  "We're good. Seriously. We're good.",
  "You may now redirect your attention elsewhere.",
  "Moisture is high. Take the win.",
};
static const char *const kSARCASTIC_VERY_WET[]={
  "Amazing. You nearly installed an indoor pool.",
  "Perhaps the plant did not need a baptism.",
  "Excellent work turning soil into a beverage.",
  "I'm drowning, but at least you care.",
  "Maybe stop watering before fish move in.",
  "Bold strategy: eliminate all air from the soil.",
  "The roots requested oxygen, not scuba gear.",
  "Watering achievement unlocked: excessive.",
  "If soggy was the objective, flawless execution.",
  "Please step away from the watering can.",
  "We've exceeded hydration and entered maritime law.",
  "This pot now has a floodplain.",
};
static const char *const kDRAMATIC_CRITICAL[]={
  "The drought has claimed nearly everything.",
  "Bring water. There is no time.",
  "My kingdom for a watering can!",
  "The roots cry out from the abyss.",
  "This may be my final moisture reading.",
  "I stand at the edge of botanical ruin.",
  "Water me, and remember me as I was.",
  "The soil has become a wasteland.",
  "Hope fades with every dry percentage point.",
  "The great thirst is upon us.",
  "My leaves demand immediate intervention.",
  "Hydration must come before the final curtain.",
};
static const char *const kDRAMATIC_VERY_DRY[]={
  "The thirst grows stronger.",
  "Soon, the soil shall become dust.",
  "I can endure, but not forever.",
  "Water approaches the top of my wish list.",
  "My roots whisper of better, wetter days.",
  "The dry season has arrived uninvited.",
  "I await the watering can with desperate hope.",
  "Every drop would be a hero now.",
  "The soil tightens its dry grip.",
  "We are nearing the danger zone.",
  "I remain brave, yet increasingly thirsty.",
  "The moisture retreats. I remain.",
};
static const char *const kDRAMATIC_DRY[]={
  "A thirst begins to stir.",
  "The soil grows restless.",
  "Soon I shall require the sacred water.",
  "I sense dryness approaching.",
  "My roots have begun their quiet plea.",
  "The hour of watering draws near.",
  "Moisture fades from this land.",
  "A drink would restore balance.",
  "I remain strong, though somewhat thirsty.",
  "The soil sends an omen: DRY.",
  "Prepare the watering can.",
  "The first chapter of thirst has begun.",
};
static const char *const kDRAMATIC_GOOD[]={
  "Balance has been restored.",
  "The roots rejoice in perfect harmony.",
  "All is well within the kingdom of soil.",
  "I flourish beneath your watch.",
  "Moisture and root exist in harmony.",
  "Today, we thrive.",
  "The soil is at peace.",
  "A golden age of hydration is upon us.",
  "No action is required. Bask in victory.",
  "The leaves stand proud.",
  "Perfect balance. Magnificent.",
  "The plant realm knows peace.",
};
static const char *const kDRAMATIC_WET[]={
  "The reservoirs are full.",
  "Water is abundant throughout the realm.",
  "The roots feast upon plentiful moisture.",
  "No more water is required today.",
  "The soil holds a generous supply.",
  "Hydration surrounds us.",
  "The watering can may rest.",
  "We possess ample reserves.",
  "The earth beneath me is richly watered.",
  "I shall drink from these stores for some time.",
  "The moisture tide is high.",
  "All thirst has been defeated.",
};
static const char *const kDRAMATIC_VERY_WET[]={
  "The flood has come.",
  "The soil can hold no more!",
  "The roots are besieged by water.",
  "Close the gates! Stop the watering!",
  "We have crossed from hydration into catastrophe.",
  "The great deluge consumes the pot.",
  "The soil has surrendered to the sea.",
  "Save the roots from this watery fate.",
  "Enough! The floodwaters rise.",
  "This pot has become an inland ocean.",
  "Let the soil breathe before all is lost.",
  "The watering must cease immediately.",
};
static const char *const kRUDE_CRITICAL[]={
  "Water me, you absolute walnut.",
  "I'm dry as hell. Fix it.",
  "For fuck's sake, get the watering can.",
  "My roots are dying of thirst over here.",
  "Quit screwing around and water me.",
  "I'm turning into crunchy bullshit.",
  "Water. Now. This isn't complicated.",
  "Holy shit, this soil is dry.",
  "I'm one bad day from becoming compost.",
  "Get off your ass and hydrate me.",
  "The dirt is basically fucking dust.",
  "I swear to chlorophyll, bring water.",
};
static const char *const kRUDE_VERY_DRY[]={
  "I'm thirsty as hell.",
  "Water me before this gets stupid.",
  "The soil is dry, genius.",
  "I could use some damn water.",
  "Quit admiring me and grab the watering can.",
  "My roots are getting pissed.",
  "This pot is dry as shit.",
  "A drink would be fucking fantastic.",
  "I'm getting crispy. Do something useful.",
  "Water soon, you magnificent procrastinator.",
  "The moisture is low and so is my patience.",
  "Don't make me get dramatic about this shit.",
};
static const char *const kRUDE_DRY[]={
  "Hey, jackass, I'm getting thirsty.",
  "Could you maybe water the damn plant?",
  "I'm a little dry. Try to keep up.",
  "Grab the watering can when you're done screwing around.",
  "The dirt's drying out, champ.",
  "I need a drink, not a motivational speech.",
  "Water would be nice, just saying.",
  "My roots are starting to bitch.",
  "Not an emergency yet. Don't make it one.",
  "I'm thirsty. This is your whole job.",
  "A little water, for crying out loud.",
  "Don't fuck this up. I'm only mildly dry.",
};
static const char *const kRUDE_GOOD[]={
  "Look at you, not killing me.",
  "I'm good. Don't fuck with it.",
  "Perfect. Somehow you nailed it.",
  "Moisture is good as hell.",
  "I'm happy. Go screw with another plant.",
  "No water needed, hero.",
  "Everything's fine. Don't get cocky.",
  "This is exactly the right amount of wet shit.",
  "Roots are happy. Nice damn job.",
  "I'm thriving despite your supervision.",
  "All good in the dirt department.",
  "You did something right. Weird.",
};
static const char *const kRUDE_WET[]={
  "I'm wet enough. Back the hell off.",
  "Put the damn watering can down.",
  "I've got plenty, thanks.",
  "No more water, you eager bastard.",
  "I'm hydrated as shit.",
  "We're good. Stop helping.",
  "Enough water. Seriously.",
  "My roots are stocked. Go away.",
  "Don't pour another damn drop.",
  "I'm wet. Mission fucking accomplished.",
  "Save the water for somebody thirsty.",
  "Step away from the hose, champ.",
};
static const char *const kRUDE_VERY_WET[]={
  "What the fuck, are you growing rice?",
  "Stop watering me, you maniac.",
  "My roots need air, not a goddamn swimming pool.",
  "Congratulations, you made mud soup.",
  "Put. The. Fucking. Watering. Can. Down.",
  "I'm drowning in your good intentions.",
  "This pot is wet as shit.",
  "Do I look like a fucking aquarium?",
  "Enough! My roots don't own snorkels.",
  "You flooded the damn place.",
  "Back off before I grow gills.",
  "Holy shit, let the soil dry.",
};
struct Pool{const char *const *items;uint16_t count;};
#define P(a) Pool{a,(uint16_t)(sizeof(a)/sizeof(a[0]))}
inline Pool pool(Theme t,State s){static const Pool p[5][6]={
{P(kCLASSIC_CRITICAL),P(kCLASSIC_VERY_DRY),P(kCLASSIC_DRY),P(kCLASSIC_GOOD),P(kCLASSIC_WET),P(kCLASSIC_VERY_WET)},
{P(kFUNNY_CRITICAL),P(kFUNNY_VERY_DRY),P(kFUNNY_DRY),P(kFUNNY_GOOD),P(kFUNNY_WET),P(kFUNNY_VERY_WET)},
{P(kSARCASTIC_CRITICAL),P(kSARCASTIC_VERY_DRY),P(kSARCASTIC_DRY),P(kSARCASTIC_GOOD),P(kSARCASTIC_WET),P(kSARCASTIC_VERY_WET)},
{P(kDRAMATIC_CRITICAL),P(kDRAMATIC_VERY_DRY),P(kDRAMATIC_DRY),P(kDRAMATIC_GOOD),P(kDRAMATIC_WET),P(kDRAMATIC_VERY_WET)},
{P(kRUDE_CRITICAL),P(kRUDE_VERY_DRY),P(kRUDE_DRY),P(kRUDE_GOOD),P(kRUDE_WET),P(kRUDE_VERY_WET)},
};uint8_t ti=(uint8_t)t,si=(uint8_t)s;return p[ti<5?ti:0][si<6?si:0];}
#undef P
inline uint16_t gcd16(uint16_t a,uint16_t b){while(b){uint16_t r=a%b;a=b;b=r;}return a;}
inline uint16_t stepFor(uint16_t n,uint32_t seed){if(n<=2)return 1;uint16_t s=(seed%(n-1))+1;while(gcd16(s,n)!=1)s=(s%(n-1))+1;return s;}
inline const char* select(Rotation&r,Theme t,State s,uint32_t seed,bool advance){
 const bool mixed=t==Theme::MIXED; Pool first=pool(mixed?Theme::CLASSIC:t,s);
 const uint16_t count=mixed?static_cast<uint16_t>(first.count*5u):first.count;if(!count)return "";
 const uint8_t rid=static_cast<uint8_t>((static_cast<uint8_t>(t)<<3)|static_cast<uint8_t>(s));
 if(r.state!=rid){r.state=rid;r.cursor=0;r.offset=seed%count;r.step=stepFor(count,seed^0x9e3779b9u);}
 else if(advance){if(++r.cursor>=count){r.cursor=0;r.offset=(r.offset+1)%count;}}
 const uint16_t i=static_cast<uint16_t>((r.offset+r.cursor*r.step)%count);
 if(!mixed)return first.items[i];
 return pool(static_cast<Theme>(i/first.count),s).items[i%first.count];
}
inline const char* themeName(Theme t){static const char*const n[]={"CLASSIC","FUNNY","SARCASTIC","DRAMATIC","RUDE","MIXED"};uint8_t i=(uint8_t)t;return n[i<6?i:5];}
} // namespace espplants_phrases
